-- Map numbers directly for AZERTY keyboard
vim.keymap.set({ 'n', 'o' }, '&', '1')
vim.keymap.set({ 'n', 'o' }, 'é', '2')
vim.keymap.set({ 'n', 'o' }, '"', '3')
vim.keymap.set({ 'n', 'o' }, '\'', '4')
vim.keymap.set({ 'n', 'o' }, '(', '5')
vim.keymap.set({ 'n', 'o' }, '-', '6')
vim.keymap.set({ 'n', 'o' }, 'è', '7')
vim.keymap.set({ 'n', 'o' }, '_', '8')
vim.keymap.set({ 'n', 'o' }, 'ç', '9')
vim.keymap.set({ 'n', 'o' }, 'à', '0')
